[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
tungstenite = "0.17"
futures = "0.3"
futures-util = "0.3.31"
url = "2.5.2"
gamesync_client = {path = "../../gamesync_client"}
